#!/usr/bin/env python3
"""
export_sigma.py - FLAME Sigma Export Pipeline

Reads all Detection Logic YAML files from DetectionLogic/, converts each
rule to Splunk SPL, Elasticsearch Lucene, and Microsoft Sentinel KQL via
pySigma backends, and writes the results to database/sigma-exports/.

Also builds per-Threat-Path (TP) packs that group exported rules by the
threat paths they reference.

Usage:
    python scripts/export_sigma.py [--root /path/to/flame-fraud]

Output structure:
    database/sigma-exports/
        splunk/<stem>.spl
        elastic/<stem>.eql
        sentinel/<stem>.kql
        sigma/<stem>.yml          (canonical Sigma copy)
        packs/
            TP-XXXX/
                README.md
                splunk/
                elastic/
                sentinel/
                sigma/
"""

import argparse
import logging
import re
import shutil
import sys
from collections import defaultdict
from pathlib import Path

import yaml

try:
    from sigma.rule import SigmaRule
except ImportError:
    sys.exit(
        "ERROR: pySigma is not installed.  Run:\n"
        "  pip install pySigma pySigma-backend-splunk "
        "pySigma-backend-elasticsearch pySigma-backend-microsoft365defender"
    )

from sigma.backends.elasticsearch import LuceneBackend
from sigma.backends.microsoft365defender import KustoBackend
from sigma.backends.splunk import SplunkBackend

# Resolve path to sigma_pipeline.py in the same directory.
_SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPT_DIR.parent))
from scripts.sigma_pipeline import flame_pipeline

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)-8s %(message)s",
)
log = logging.getLogger("export_sigma")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TUNING_COMMENT_SPL = (
    "` FLAME logsource mapping -- field names, index, and sourcetype "
    "require environment-specific tuning. `"
)
TUNING_COMMENT_EQL = (
    "/* FLAME logsource mapping -- field names and index patterns "
    "require environment-specific tuning. */"
)
TUNING_COMMENT_KQL = (
    "// FLAME logsource mapping -- table names and field names "
    "require environment-specific tuning."
)

# Map of (backend_label, file_extension, tuning_comment, BackendClass)
BACKEND_SPECS: list[tuple[str, str, str, type]] = [
    ("splunk", ".spl", TUNING_COMMENT_SPL, SplunkBackend),
    ("elastic", ".eql", TUNING_COMMENT_EQL, LuceneBackend),
    ("sentinel", ".kql", TUNING_COMMENT_KQL, KustoBackend),
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_tp_title(tp_id: str, tp_dir: Path) -> str:
    """Try to read the title of a Threat Path from its markdown file.

    Falls back to the TP id if the file cannot be found or parsed.
    """
    # TP files are named like TP-0001-treasury-mgmt-ato-malvertising.md
    candidates = list(tp_dir.glob(f"{tp_id}-*.md"))
    if not candidates:
        return tp_id
    tp_path = candidates[0]
    try:
        text = tp_path.read_text(encoding="utf-8")
        # Try YAML frontmatter first (inside ```yaml block)
        m = re.search(r'title:\s*"?([^"\n]+)"?', text)
        if m:
            return m.group(1).strip()
        # Fall back to H1
        m = re.search(r'^#\s+(.+)', text, re.MULTILINE)
        if m:
            return m.group(1).strip()
    except Exception:
        pass
    return tp_id


def _write_pack_readme(
    pack_dir: Path,
    tp_id: str,
    tp_title: str,
    rules_info: list[dict],
) -> None:
    """Write a README.md for a per-TP detection pack."""
    lines = [
        f"# {tp_id} Detection Pack",
        "",
        f"Detection rules mapped to **{tp_title}**.",
        "",
        "## Rules",
        "",
        "| Rule ID | Title | Level | Phase |",
        "|---------|-------|-------|-------|",
    ]
    for r in sorted(rules_info, key=lambda x: x["id"]):
        lines.append(
            f"| {r['id']} | {r['title']} | {r['level']} | {r['phase']} |"
        )
    lines += [
        "",
        "## Formats",
        "",
        "- `splunk/` -- Splunk SPL queries",
        "- `elastic/` -- Elasticsearch Lucene queries",
        "- `sentinel/` -- Microsoft Sentinel KQL queries",
        "- `sigma/` -- Canonical Sigma YAML rules",
        "",
        "---",
        "",
        "*Generated by the FLAME Sigma Export Pipeline.*",
        "",
    ]
    (pack_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def _extract_dl_id(stem: str) -> str:
    """Extract the DL-XXXX id from a filename stem like DL-0001-mule-account-velocity."""
    m = re.match(r"(DL-\d+)", stem)
    return m.group(1) if m else stem


# ---------------------------------------------------------------------------
# Pseudocode fallback
# ---------------------------------------------------------------------------

def _generate_pseudocode_fallback(yaml_text: str, meta: dict) -> str:
    """Generate a pseudocode fallback for rules that pySigma cannot convert.

    This applies to rules using aggregation/correlation syntax (pipe |, near,
    temporal, compare) that require SIEM-native implementation.
    """
    title = meta.get("title", "Unknown")
    description = meta.get("description", "")
    level = meta.get("level", "unknown")
    phase = meta.get("cfpf_phase", "?")
    threat_paths = meta.get("threat_paths", []) or []

    # Extract the detection block from YAML
    detection = meta.get("detection", {})
    logsource = meta.get("logsource", {})

    lines = [
        "# " + "=" * 70,
        f"# FLAME Detection Rule: {title}",
        "# " + "=" * 70,
        "#",
        "# This rule uses aggregation/correlation logic that requires",
        "# SIEM-native implementation. It cannot be auto-converted to",
        "# SPL/Lucene/KQL by pySigma backends.",
        "#",
        f"# Level: {level}",
        f"# CFPF Phase: {phase}",
        f"# Threat Paths: {', '.join(threat_paths) if threat_paths else 'N/A'}",
        "#",
        f"# Description:",
    ]

    # Wrap description at ~70 chars
    if description:
        words = description.split()
        line = "#   "
        for word in words:
            if len(line) + len(word) + 1 > 75:
                lines.append(line)
                line = "#   " + word
            else:
                line += " " + word if line != "#   " else word
        if line.strip("#").strip():
            lines.append(line)

    lines.append("#")
    lines.append("# " + "-" * 70)
    lines.append("# Log Source")
    lines.append("# " + "-" * 70)

    if logsource:
        for key, val in logsource.items():
            lines.append(f"#   {key}: {val}")

    lines.append("#")
    lines.append("# " + "-" * 70)
    lines.append("# Detection Logic (Sigma YAML)")
    lines.append("# " + "-" * 70)

    if detection:
        detection_yaml = yaml.dump(detection, default_flow_style=False, sort_keys=False)
        for det_line in detection_yaml.strip().split("\n"):
            lines.append(f"#   {det_line}")

    lines.append("#")

    # Add false positives
    fps = meta.get("falsepositives", [])
    if fps:
        lines.append("# " + "-" * 70)
        lines.append("# Known False Positives")
        lines.append("# " + "-" * 70)
        for fp in fps:
            lines.append(f"#   - {fp}")
        lines.append("#")

    lines.append("# " + "=" * 70)
    lines.append("# Implementation Notes:")
    lines.append("#   - Review the condition syntax and implement using your SIEM's")
    lines.append("#     native aggregation/correlation capabilities")
    lines.append("#   - Splunk: Use 'stats' or 'transaction' commands")
    lines.append("#   - Elastic: Use EQL sequences or aggregation queries")
    lines.append("#   - Sentinel: Use KQL summarize/make-series operators")
    lines.append("# " + "=" * 70)
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="FLAME Sigma Export Pipeline")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Root of the flame-fraud repo (default: auto-detect)",
    )
    args = parser.parse_args()
    root: Path = args.root.resolve()

    dl_dir = root / "DetectionLogic"
    tp_dir = root / "ThreatPaths"
    export_dir = root / "database" / "sigma-exports"

    if not dl_dir.is_dir():
        log.error("DetectionLogic/ directory not found at %s", dl_dir)
        sys.exit(1)

    # Create output directories
    for sub in ("splunk", "elastic", "sentinel", "sigma", "pseudocode"):
        (export_dir / sub).mkdir(parents=True, exist_ok=True)

    # Build the FLAME processing pipeline
    pipeline = flame_pipeline()

    # Instantiate backends with collect_errors=True so a single bad rule
    # doesn't abort the whole run.
    backends: list[tuple[str, str, str, object]] = []
    for label, ext, comment, cls in BACKEND_SPECS:
        backends.append((label, ext, comment, cls(processing_pipeline=pipeline, collect_errors=True)))

    # ------------------------------------------------------------------
    # Pass 1: Convert all rules
    # ------------------------------------------------------------------
    dl_files = sorted(dl_dir.glob("*.yml"))
    if not dl_files:
        log.error("No .yml files found in %s", dl_dir)
        sys.exit(1)
    log.info("Found %d Detection Logic rules in %s", len(dl_files), dl_dir)

    # Track per-TP associations: tp_id -> list of rule info dicts
    tp_rules: dict[str, list[dict]] = defaultdict(list)

    # Track per-rule exported file stems so we can copy into packs
    exported_stems: dict[str, dict[str, Path]] = {}  # stem -> {label: path}

    succeeded = 0
    failed = 0
    partial = 0  # at least one backend succeeded
    pseudocode_count = 0

    for dl_path in dl_files:
        stem = dl_path.stem  # e.g. DL-0001-mule-account-velocity
        dl_id = _extract_dl_id(stem)
        yaml_text = dl_path.read_text(encoding="utf-8")

        # Parse YAML for metadata (threat_paths, cfpf_phase, level, title)
        try:
            meta = yaml.safe_load(yaml_text)
        except yaml.YAMLError as exc:
            log.warning("YAML parse error in %s: %s -- skipping", dl_id, exc)
            failed += 1
            continue

        title = meta.get("title", stem)
        level = meta.get("level", "unknown")
        phase = meta.get("cfpf_phase", "?")
        threat_paths = meta.get("threat_paths", []) or []

        # Build SigmaRule
        try:
            rule = SigmaRule.from_yaml(yaml_text)
        except Exception as exc:
            log.warning("SigmaRule parse error in %s: %s -- skipping", dl_id, exc)
            failed += 1
            continue

        # Copy canonical Sigma YAML
        sigma_dst = export_dir / "sigma" / f"{stem}.yml"
        sigma_dst.write_text(yaml_text, encoding="utf-8")

        # Convert via each backend
        rule_ok = 0
        exported_stems[stem] = {}

        for label, ext, comment, backend in backends:
            try:
                results = backend.convert_rule(rule)  # type: ignore[union-attr]

                # Check if backend collected errors instead of raising
                if not results:
                    # Check backend.errors for this rule
                    if hasattr(backend, "errors") and backend.errors:
                        last_err = backend.errors[-1]
                        err_msg = str(last_err[1]) if isinstance(last_err, tuple) else str(last_err)
                        log.warning(
                            "  %s [%s] conversion error (collected): %s",
                            dl_id, label, err_msg[:120],
                        )
                        continue

                query_text = "\n".join(str(r) for r in results)
                output_text = f"{comment}\n\n{query_text}\n"

                out_path = export_dir / label / f"{stem}{ext}"
                out_path.write_text(output_text, encoding="utf-8")
                exported_stems[stem][label] = out_path
                rule_ok += 1

            except Exception as exc:
                log.warning(
                    "  %s [%s] conversion failed: %s", dl_id, label, str(exc)[:120]
                )

        # Always record sigma copy path
        exported_stems[stem]["sigma"] = sigma_dst

        if rule_ok == len(backends):
            succeeded += 1
        elif rule_ok > 0:
            partial += 1
        else:
            # All backends failed — generate pseudocode fallback
            pseudo_text = _generate_pseudocode_fallback(yaml_text, meta)
            pseudo_path = export_dir / "pseudocode" / f"{stem}.txt"
            pseudo_path.write_text(pseudo_text, encoding="utf-8")
            exported_stems[stem]["pseudocode"] = pseudo_path
            pseudocode_count += 1
            log.info("  %s -> pseudocode fallback (aggregation/correlation rule)", dl_id)

        # Record TP associations
        rule_info = {
            "id": dl_id,
            "stem": stem,
            "title": title,
            "level": level,
            "phase": phase,
        }
        for tp_id in threat_paths:
            tp_rules[tp_id].append(rule_info)

    # ------------------------------------------------------------------
    # Pass 2: Build per-TP packs
    # ------------------------------------------------------------------
    packs_dir = export_dir / "packs"
    log.info("Building per-TP packs for %d threat paths...", len(tp_rules))

    for tp_id, rules_info in sorted(tp_rules.items()):
        pack_dir = packs_dir / tp_id
        for sub in ("splunk", "elastic", "sentinel", "sigma", "pseudocode"):
            (pack_dir / sub).mkdir(parents=True, exist_ok=True)

        # Copy exported files into the pack
        for rinfo in rules_info:
            stem = rinfo["stem"]
            stem_exports = exported_stems.get(stem, {})
            for label, src_path in stem_exports.items():
                dst = pack_dir / label / src_path.name
                try:
                    shutil.copy2(src_path, dst)
                except Exception as exc:
                    log.warning(
                        "  Failed to copy %s to pack %s: %s",
                        src_path.name, tp_id, exc,
                    )

        # Write README
        tp_title = _read_tp_title(tp_id, tp_dir)
        _write_pack_readme(pack_dir, tp_id, tp_title, rules_info)
        log.info("  Pack %s: %d rules", tp_id, len(rules_info))

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    total = len(dl_files)
    log.info("")
    log.info("=" * 60)
    log.info("FLAME Sigma Export Complete")
    log.info("=" * 60)
    log.info("  Total rules:      %d", total)
    log.info("  Fully converted:  %d  (all 3 backends)", succeeded)
    log.info("  Partial:          %d  (at least 1 backend)", partial)
    log.info("  Pseudocode only:  %d  (aggregation/correlation)", pseudocode_count)
    log.info("  Failed:           %d  (parse errors)", failed)
    log.info("  TP packs:         %d", len(tp_rules))
    log.info("  Output directory:  %s", export_dir)
    log.info("=" * 60)


if __name__ == "__main__":
    main()
